apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: my-argocd
  - kind: ServiceAccount
    name: argocd-server
    namespace: my-argocd
